### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by mikaelcom** [coduo/php-humanizer#83] opened 2016-08-03 04:42 UTC
Hi,

I'm facing an issue on `PHP 5.5.9-1ubuntu4.19 (cli)` when using NumberHumanizer::binarySuffix as I'm having a PHP warning saying `Division by zero`.

I digged by myself and found that the array
```php
private $binaryPrefixes = array(
        1125899906842624 => '#.## PB',
        1099511627776 => '#.## TB',
        1073741824 => '#.## GB',
        1048576 => '#.## MB',
        1024 => '#.# kB',
        0 => '# bytes',
    );
```
is actually returned such as
```php
Array
(
    [0] => # bytes
    [1073741824] => #.## GB
    [1048576] => #.## MB
    [1024] => #.# kB
)
```

Did anyone faced this issue already?

Thanks by the way

**Comment by norzechowicz** [comment] 2016-08-04 10:27
Hey @mikaelcom could you also put here some code examples that throws this warning?

**Comment by mikaelcom** [comment] 2016-08-04 11:10
I'm using the ` NumberHumanizer::binarySuffix(86450)` for example and this throws this warning

**Comment by norzechowicz** [comment] 2016-08-08 20:00
@mikaelcom as you can see in #86 I'm not able to reproduce that issue : <

**Comment by norzechowicz** [comment] 2016-08-09 19:14
Closing since I'm not able to reproduce that issue.

**Comment by mikaelcom** [comment] 2016-08-10 06:49
Hi,
I have a clue, I tested it under a 32-bit OS :wink:

**Comment by norzechowicz** [comment] 2016-08-10 07:08
Ok, so I'm reopening it

**Closed** 2016-10-12 18:38 UTC
Labels: require investigation
